[package]
name = "express-luck-hungary-physical-inventory-recording"
version = "0.1.0"
description = "Inventory Scanner PoC - Tauri + Next.js"
authors = ["you"]
edition = "2021"

[lib]
name = "express_luck_hungary_physical_inventory_recording_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
serde_json = "1"
serde = { version = "1", features = ["derive"] }
tauri = { version = "2", features = ["devtools"] }
tauri-plugin-opener = "2"

[features]
default = [ "custom-protocol" ]
custom-protocol = [ "tauri/custom-protocol" ]
