<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net8.0-android</TargetFrameworks>
    <UseMaui>true</UseMaui>
    <SingleProject>true</SingleProject>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <ApplicationTitle>Express Luck</ApplicationTitle>
    <AndroidPackageFormat>apk</AndroidPackageFormat>
    <SupportedOSPlatformVersion>21</SupportedOSPlatformVersion>
    <ApplicationId>com.express.luck.hungary</ApplicationId>
  </PropertyGroup>

  <ItemGroup>
    <MauiAsset Include="Resources\\**" />
  </ItemGroup>
</Project>
