name: express_luck_inventory_scanner
description: Proof-of-concept inventory scanner app with profile and Power Automate submit.
publish_to: 'none'

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.2.2
  shared_preferences: ^2.2.3
  mobile_scanner: ^5.1.1
  uuid: ^4.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
